### ISSUE TITLE
 ‘UXR_REQUESTER_ID’ undeclared in rmw_node.c

### ISSUE THREAD

**Issue by Sdehnavi** [micro-ROS/rmw-microxrcedds#47]
Hi,

I get the following error in rmw_node.c
rmw_client.c:110:69: error: ‘UXR_REQUESTER_ID’ undeclared (first use in this function); did you mean ‘UXR_REQUEST_NONE’?
     custom_client->client_id = uxr_object_id(custom_node->id_gen++, UXR_REQUESTER_ID);

Would you please tell me where UXR_REQUESTER_ID has been defined?
Thanks!

**Comment by pablogs9** [comment]
Hello, can you detail which is your Micro-ROS setup?

It seems that you have a version of Micro-XRCE-DDS-Client without services, because the value you are refering is related to services implementation. They are implemented in this commit: https://github.com/eProsima/Micro-XRCE-DDS-Client/commit/fd52a2505f5efc0ce7071a7780035c0fc82076bf

**Comment by Sdehnavi** [comment]
Thanks @pablogs9 
I changed to the crystal version and now it has been solved. But I have another issue which is related to type_support. I will create a new issue for it.
